name: Update documentation
on:
  release:
    types: [ published ]
jobs:
  update-api-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate API documentation
        run: ./gradlew dokkaHtml
      - name: Deploy API documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: lib/build/dokka/html